import { useEffect, useState } from 'react';
import { MapContainer, TileLayer, CircleMarker, Popup, useMap } from 'react-leaflet';
import { Layers3, LocateFixed, Minus, Plus, ShieldAlert, RefreshCw } from 'lucide-react';
import { api } from '../services/api';

type LayerKey='risk'|'water'|'shelters'|'infra';
export default function MapPanel(){const [layers,setLayers]=useState<Record<LayerKey,boolean>>({risk:true,water:true,shelters:true,infra:true});const [zoom,setZoom]=useState(13);const [data,setData]=useState<any>();const [error,setError]=useState('');
 useEffect(()=>{api.getGeo().then(setData).catch(e=>setError(e.message)); const onP=(e:any)=>setData((d:any)=>d?({...d,areas:d.areas.map((a:any)=>a.id===(e.detail?.locationId||'zone-01')?({...a,risk:Math.round((e.detail?.flood_probability||a.risk/100)*100),depth:e.detail?.estimated_water_depth??a.depth,level:e.detail?.risk_level??a.level}):a)}):d); const onS=(e:any)=>setData((d:any)=>d?({...d,waterBodies:e.detail?.waterBodies||d.waterBodies}):d); window.addEventListener('jalrakshak-prediction',onP);window.addEventListener('jalrakshak-simulation',onS);return()=>{window.removeEventListener('jalrakshak-prediction',onP);window.removeEventListener('jalrakshak-simulation',onS)}},[]); const areas=data?.areas||[];const waters=data?.waterBodies||[];const shelters=data?.shelters||[];const infra=data?.infrastructure||[];
 return <div className="map-wrap">{error&&<div className="map-error"><RefreshCw size={14}/> {error}</div>}<MapContainer center={[28.621,77.216]} zoom={zoom} scrollWheelZoom><MapController zoom={zoom}/><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{layers.risk&&areas.map((a:any)=><CircleMarker key={a.id} center={[a.lat,a.lng]} radius={a.risk>75?17:a.risk>50?13:10} pathOptions={{color:a.risk>=80?'#ef5a67':a.risk>=60?'#f1a34b':'#55c596',fillColor:a.risk>=80?'#ef5a67':a.risk>=60?'#f1a34b':'#55c596',fillOpacity:.72,weight:2}}><Popup><b>{a.name}</b><br/>Risk: {a.risk}/100<br/>Depth: {Number(a.depth).toFixed(2)} m<br/>Drain utilization: {a.drainUtilization??a.drain}%</Popup></CircleMarker>)}{layers.water&&waters.map((w:any)=><CircleMarker key={w.id} center={[w.lat,w.lng]} radius={11} pathOptions={{color:'#4ba9d1',fillColor:'#4ba9d1',fillOpacity:.45,weight:1.5,dashArray:'4 3'}}><Popup><b>Water body · {w.name}</b><br/>Storage: {w.levelPct??w.level}%<br/>Overflow: {w.overflowRisk??w.status}</Popup></CircleMarker>)}{layers.shelters&&shelters.map((s:any)=><CircleMarker key={s.id} center={[s.lat,s.lng]} radius={7} pathOptions={{color:'#4bd18a',fillColor:'#4bd18a',fillOpacity:.9,weight:2}}><Popup><b>Relief shelter · {s.name}</b><br/>Available: {s.available??s.capacity-s.occupied} / {s.capacity}</Popup></CircleMarker>)}{layers.infra&&infra.map((i:any)=><CircleMarker key={i.id} center={[i.lat,i.lng]} radius={7} pathOptions={{color:'#d9e5ef',fillColor:'#15293b',fillOpacity:1,weight:2}}><Popup><b>{i.type} · {i.name}</b><br/>Status: {i.status}</Popup></CircleMarker>)}</MapContainer><div className="map-toolbar"><button onClick={()=>setZoom(z=>Math.min(17,z+1))} aria-label="Zoom in"><Plus size={15}/></button><button onClick={()=>setZoom(z=>Math.max(10,z-1))} aria-label="Zoom out"><Minus size={15}/></button><button onClick={()=>setZoom(13)} aria-label="Reset view"><LocateFixed size={15}/></button></div><div className="layer-panel"><div className="layer-title"><Layers3 size={13}/>MAP LAYERS</div><LayerButton label="Flood risk" active={layers.risk} tone="risk" onClick={()=>setLayers(v=>({...v,risk:!v.risk}))}/><LayerButton label="Water bodies" active={layers.water} tone="water" onClick={()=>setLayers(v=>({...v,water:!v.water}))}/><LayerButton label="Shelters" active={layers.shelters} tone="shelter" onClick={()=>setLayers(v=>({...v,shelters:!v.shelters}))}/><LayerButton label="Critical infrastructure" active={layers.infra} tone="infra" onClick={()=>setLayers(v=>({...v,infra:!v.infra}))}/></div><div className="map-legend"><b>FLOOD RISK</b><span><i className="critical"></i>Critical</span><span><i className="high"></i>High</span><span><i className="moderate"></i>Moderate</span><span><i className="low"></i>Low</span></div><div className="map-tag"><ShieldAlert size={12}/> LIVE +2H FORECAST</div></div>}
function MapController({zoom}:{zoom:number}){const map=useMap();useEffect(()=>{map.setZoom(zoom)},[zoom,map]);return null}
function LayerButton({label,active,tone,onClick}:{label:string;active:boolean;tone:string;onClick:()=>void}){return <button className={`layer-btn ${active?'active':''}`} onClick={onClick}><span className={`layer-dot ${tone}`}></span>{label}<span className="layer-state">{active?'ON':'OFF'}</span></button>}
