import { useEffect, useState, type FormEvent } from 'react';
import { NavLink, Route, Routes, useLocation } from 'react-router-dom';
import { Bell, CloudRain, Command, Database, History, LayoutDashboard, LogOut, Menu, Route as RouteIcon, SlidersHorizontal, UserRound, X, ShieldAlert } from 'lucide-react';
import Dashboard from './pages/Dashboard'; import Admin from './pages/Admin'; import Simulation from './pages/Simulation'; import Alerts from './pages/Alerts'; import Routing from './pages/Routing'; import HistoryPage from './pages/HistoryPage'; import DataModels from './pages/DataModels'; import Chat from './components/Chat'; import { api } from './services/api';

const nav=[['/','Command Center',LayoutDashboard],['/simulation','What-If Simulation',SlidersHorizontal],['/routing','Safe Routing',RouteIcon],['/alerts','Alerts & Response',Bell],['/history','Historical Analysis',History],['/data-models','Data & Models',Database],['/admin','Admin',ShieldAlert]] as const;

export default function App(){
 const [open,setOpen]=useState(false); const [user,setUser]=useState<any>(null); const [checking,setChecking]=useState(true); const loc=useLocation();
 useEffect(()=>{ let alive=true; api.me().then(r=>alive&&setUser(r.user)).catch(()=>{}).finally(()=>alive&&setChecking(false)); const fn=()=>{setUser(null);setChecking(false)}; window.addEventListener('jalrakshak-auth-expired',fn); return()=>{alive=false;window.removeEventListener('jalrakshak-auth-expired',fn)} },[]);
 if(checking) return <div className="boot"><CloudRain size={28}/><b>JALRAKSHAK</b><span>Loading secure control room…</span></div>;
 if(!user) return <Login onLogin={setUser}/>;
 const title=nav.find(x=>x[0]===loc.pathname)?.[1]||'Command Center';
 const logout=()=>{api.logout();setUser(null)};
 return <div className="app-shell"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><div className="brand-mark"><CloudRain size={21}/></div><div><b>JALRAKSHAK</b><span>URBAN FLOOD INTELLIGENCE</span></div><button className="icon-btn mobile-only" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="synthetic"><span></span> SYNTHETIC PILOT CITY <small>DEMO</small></div><nav>{nav.map(([path,label,Icon])=><NavLink key={path} to={path} end={path==='/' } onClick={()=>setOpen(false)} className={({isActive})=>isActive?'active':''}><Icon size={18}/><span>{label}</span>{label==='Alerts & Response'&&<i>3</i>}</NavLink>)}</nav><div className="side-bottom"><div className="system"><span className="dot"></span><div><b>API authenticated</b><small>{user.role} · {user.email}</small></div></div><button className="user-card" onClick={logout}><div className="avatar">{user.email.slice(0,2).toUpperCase()}</div><div><b>{user.role}</b><small>SECURE SESSION</small></div><LogOut size={15}/></button></div></aside><main className="main"><header><button className="icon-btn mobile-only" onClick={()=>setOpen(true)}><Menu size={20}/></button><div><div className="eyebrow">JALRAKSHAK / OPERATIONS</div><h1>{title}</h1></div><div className="header-actions"><div className="live"><span></span> LIVE MODEL</div><button className="icon-btn"><Bell size={18}/><em>3</em></button><button className="profile" onClick={logout}><div className="avatar"><UserRound size={15}/></div><span>{user.role}</span><LogOut size={15}/></button></div></header><div className="content"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/simulation" element={<Simulation/>}/><Route path="/routing" element={<Routing/>}/><Route path="/alerts" element={<Alerts/>}/><Route path="/history" element={<HistoryPage/>}/><Route path="/data-models" element={<DataModels/>}/><Route path="/admin" element={<Admin/>}/></Routes></div><Chat/><footer><span>JALRAKSHAK v1.1</span><span>Data shown is synthetic pilot-city data · Not municipal live data</span><span>API gateway: <b>authenticated</b></span></footer></main></div>
}

function Login({onLogin}:{onLogin:(u:any)=>void}){
 const [email,setEmail]=useState('authority@jalrakshak.local'); const [password,setPassword]=useState('Jal@1234'); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');setLoading(true);try{const r=await api.login(email,password);onLogin(r.user)}catch(err){setError(err instanceof Error?err.message:'Login failed')}finally{setLoading(false)}};
 return <div className="login"><form className="login-card" onSubmit={submit}><div className="brand large"><div className="brand-mark"><CloudRain size={25}/></div><div><b>JALRAKSHAK</b><span>URBAN FLOOD INTELLIGENCE</span></div></div><div className="login-copy"><div className="eyebrow">SECURE CONTROL ROOM</div><h1>Welcome back.</h1><p>Sign in to access live backend-backed flood intelligence.</p></div><label>EMAIL ADDRESS<input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="username"/></label><label>PASSWORD<input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="current-password"/></label>{error&&<div className="login-error">{error}</div>}<button className="primary wide" disabled={loading}>{loading?<><span className="button-spinner"/>Signing in…</>:<>Enter command center <Command size={17}/></>}</button><div className="demo-note"><ShieldAlert size={14}/> Demo: authority@jalrakshak.local / Jal@1234</div></form></div>
}
